# Generated by Django 3.0.2 on 2020-02-10 23:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200122_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=300)),
                ('account_number', models.TextField()),
                ('account_description', models.TextField()),
                ('account_category', models.CharField(max_length=300)),
                ('account_subcategory', models.CharField(max_length=300)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_created', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.CharField(max_length=300)),
                ('statement', models.FileField(upload_to='')),
                ('comment', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
