# Generated by Django 3.0.2 on 2020-02-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
