# Generated by Django 3.0.2 on 2020-02-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='statement',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
