# Generated by Django 3.0.2 on 2020-02-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200212_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attempts',
        ),
    ]
