# Generated by Django 3.0.2 on 2020-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200220_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attempts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
