# Generated by Django 3.0.2 on 2020-02-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_historicaluseraccount_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
