# Generated by Django 3.0.2 on 2020-02-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200216_0555'),
        ('accounts', '0005_auto_20200215_2141'),
    ]

    operations = [
    ]
