# Generated by Django 3.0.2 on 2020-02-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200226_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLedger',
        ),
    ]
