# Generated by Django 3.0.2 on 2020-02-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_historicalledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='initial_balance',
            new_name='initial_journal_balance',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='balance',
            new_name='journal_balance',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='credit',
            new_name='journal_credit',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='debit',
            new_name='journal_debit',
        ),
    ]
