# Generated by Django 3.0.2 on 2020-02-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ledger_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
