# Generated by Django 3.0.2 on 2020-02-26 01:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_delete_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Journal_name', models.CharField(max_length=300, unique=True)),
                ('Journal_number', models.PositiveIntegerField(unique=True)),
                ('Journal_description', models.TextField(blank=True, null=True)),
                ('initial_journal_balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('journal_debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
