# Generated by Django 3.0.2 on 2020-03-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_historicalledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['Journal_name']},
        ),
    ]
