# Generated by Django 3.0.2 on 2020-03-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200302_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={},
        ),
    ]
