# Generated by Django 3.0.2 on 2020-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200302_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournal',
            name='source_document',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='source_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
