# Generated by Django 3.0.2 on 2020-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200308_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='source_document',
            field=models.FileField(blank=True, null=True, upload_to='source_docs'),
        ),
    ]
