# Generated by Django 3.0.2 on 2020-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200308_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournal',
            name='pending',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='pending',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
