# Generated by Django 3.0.2 on 2020-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200309_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournal',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, null=True),
        ),
    ]
