# Generated by Django 3.0.2 on 2020-03-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200311_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljournal',
            old_name='reason',
            new_name='reason_for_rejection',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='reason',
            new_name='reason_for_rejection',
        ),
    ]
