# Generated by Django 3.0.4 on 2020-03-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200311_1749'),
        ('accounts', '0030_auto_20200311_1504'),
    ]

    operations = [
    ]
