# Generated by Django 3.0.4 on 2020-04-15 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_merge_20200311_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournal',
            name='initial_journal_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='initial_journal_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
