# Generated by Django 3.0.2 on 2020-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200329_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
