# Generated by Django 3.0.4 on 2020-04-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_statements'),
        ('accounts', '0033_auto_20200415_1634'),
    ]

    operations = [
    ]
