<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_20200415_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournal',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
        migrations.AddField(
            model_name='journal',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
    ]
=======
# Generated by Django 3.0.2 on 2020-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_20200415_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournal',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
        migrations.AddField(
            model_name='journal',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
    ]
>>>>>>> 46394645150eb39ce119f55bbfe16c562db951c4
