# Generated by Django 3.0.2 on 2020-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200416_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustingjournalentry',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
        migrations.AddField(
            model_name='historicaladjustingjournalentry',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Expense'), (2, 'Revenue'), (3, 'NA')], default=3),
        ),
    ]
