<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200416_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Net_Profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 3.0.2 on 2020-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200416_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Net_Profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
>>>>>>> 46394645150eb39ce119f55bbfe16c562db951c4
