# Generated by Django 3.0.2 on 2020-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_statements_net_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaladjustingjournalentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='historicaladjustingjournalentry',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='AdjustingJournalEntry',
        ),
        migrations.DeleteModel(
            name='HistoricalAdjustingJournalEntry',
        ),
    ]
