# Generated by Django 3.0.2 on 2020-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200418_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Ending_Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
