# Generated by Django 3.0.2 on 2020-04-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_statements_ending_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
