# Generated by Django 3.0.2 on 2020-02-13 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_historicaluseraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='account_category',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='account_name',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='account_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='account_subcategory',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='order',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_category',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_name',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_subcategory',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='order',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
